"""initial schema

Revision ID: 77e8c27216a6
Revises: 
Create Date: 2026-03-05 21:04:57.151227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77e8c27216a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('builders',
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('headquarters_city', sa.String(length=255), nullable=True),
    sa.Column('headquarters_state', sa.String(length=2), nullable=True),
    sa.Column('geographic_regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_title', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('primary_contact_linkedin', sa.Text(), nullable=True),
    sa.Column('active_project_count', sa.Integer(), nullable=True),
    sa.Column('pipeline_value_usd', sa.Float(), nullable=True),
    sa.Column('historical_units_delivered', sa.Integer(), nullable=True),
    sa.Column('historical_sqft_delivered', sa.Integer(), nullable=True),
    sa.Column('asset_specialization', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_partnership_model', sa.String(length=50), nullable=True),
    sa.Column('bonding_capacity_single_usd', sa.Float(), nullable=True),
    sa.Column('bonding_capacity_aggregate_usd', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builders_company_name'), 'builders', ['company_name'], unique=False)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('access_method', sa.String(length=50), nullable=False),
    sa.Column('scrape_complexity', sa.String(length=50), nullable=False),
    sa.Column('geographic_coverage', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('scrape_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_table('developments',
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('permit_type', sa.String(length=50), nullable=False),
    sa.Column('permit_status', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=255), nullable=False),
    sa.Column('address_street', sa.String(length=500), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('apn', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zoning_current', sa.String(length=50), nullable=True),
    sa.Column('zoning_proposed', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valuation_usd', sa.Float(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('total_sqft', sa.Integer(), nullable=True),
    sa.Column('lot_size_acres', sa.Float(), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=500), nullable=True),
    sa.Column('owner_entity_type', sa.String(length=50), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_mailing_address', sa.Text(), nullable=True),
    sa.Column('applicant_name', sa.String(length=500), nullable=True),
    sa.Column('applicant_phone', sa.String(length=20), nullable=True),
    sa.Column('applicant_email', sa.String(length=255), nullable=True),
    sa.Column('contractor_name', sa.String(length=500), nullable=True),
    sa.Column('contractor_license', sa.String(length=100), nullable=True),
    sa.Column('architect_name', sa.String(length=500), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developments_address_city'), 'developments', ['address_city'], unique=False)
    op.create_index(op.f('ix_developments_county'), 'developments', ['county'], unique=False)
    op.create_index(op.f('ix_developments_permit_status'), 'developments', ['permit_status'], unique=False)
    op.create_index(op.f('ix_developments_permit_type'), 'developments', ['permit_type'], unique=False)
    op.create_index(op.f('ix_developments_property_type'), 'developments', ['property_type'], unique=False)
    op.create_table('improvement_logs',
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('strategy_change', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_logs_metric_type'), 'improvement_logs', ['metric_type'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_table('leads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('development_id', sa.UUID(), nullable=True),
    sa.Column('builder_id', sa.UUID(), nullable=True),
    sa.Column('lead_type', sa.String(length=50), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_via', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builders.id'], ),
    sa.ForeignKeyConstraint(['development_id'], ['developments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_builder_id'), 'leads', ['builder_id'], unique=False)
    op.create_index(op.f('ix_leads_development_id'), 'leads', ['development_id'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_lead_type'), 'leads', ['lead_type'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leads_tier'), 'leads', ['tier'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_table('raw_collections',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_collections_content_hash'), 'raw_collections', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_collections_source_id'), 'raw_collections', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_collections_status'), 'raw_collections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_collections_status'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_source_id'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_content_hash'), table_name='raw_collections')
    op.drop_table('raw_collections')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_leads_tier'), table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_type'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_development_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_builder_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_improvement_logs_metric_type'), table_name='improvement_logs')
    op.drop_table('improvement_logs')
    op.drop_index(op.f('ix_developments_property_type'), table_name='developments')
    op.drop_index(op.f('ix_developments_permit_type'), table_name='developments')
    op.drop_index(op.f('ix_developments_permit_status'), table_name='developments')
    op.drop_index(op.f('ix_developments_county'), table_name='developments')
    op.drop_index(op.f('ix_developments_address_city'), table_name='developments')
    op.drop_table('developments')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_builders_company_name'), table_name='builders')
    op.drop_table('builders')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
